- fas/api/people.py
This led to a runtime error when accessing
`/api/people/username/admin`.
> Fix a typo that led to a runtime error.

- fas/models/group.py
- fas/models/people.py
To be consistent with StartTimeStamp/EndTimeStamp in the general result
template. Makes parsing the dates into a date format in other
environments a bit easier since they are all the same format.
Signed-off-by: Ricky Elrod <ricky@elrod.me>
> Make JSON `CreationDate`s be in isoformat

- fas/api/__init__.py
- fas/models/group.py
- fas/models/people.py
- fas/utils/__init__.py
See the comment above `fix_utc_iso_format` in `fas/utils/__init__.py`,
but the general idea is that Python's datetime carries no timezone
information. So when it's used for UTC, it breaks the
specification (which says that it, if no `Z` or `+HHMM` or `-HHMM` is
specified, then the time should be treated as local time).
Furthermore, since it's invalid, it makes it impossible to correctly
parse in environments which are more strict about following the ISO
format, since such environments are timezone-aware and won't know which
timezone to tag the timestamp with.
Note that this fix is very unideal: Since Python is unityped, there's no
way to ensure that the object passed to `fix_utc_iso_format` is really a
UTC time. This means that if a local time is passed to
`fix_utc_iso_format`, we will …
> Work around Python's invalid ISO format

- plugins/fas-plugin-yubikey/fas_yubikey/__init__.py
Previously, code was added to publish fedmsg messages when the user
updated their yubikey through the web interface.
This adds the same message to the JSON interface, so that
fedora-burn-yubikey usage will kick off the message.
> Also publish fedmsg when yubikey updated via json api.

- scripts/export-bugzilla.py
We are not storing token file on disc as we were not storing cookie file on disc
> Update export-bugzilla so that it does not to store the token file on disc

- fas/security.py
This fixes a fatal that occurs when you attempt to log in using an account that is in pending state.
> Fix reference to missing field by adding the field

- fas/validators.py
Looks like exceptions only get treated correctly on validate_python not
on _to_python, so removing the type conversion should fix the error
> Amtempt to fix github issue #118

- development.ini
- fas/templates/fedoraproject/site.xhtml
This will add a little menu on the bottom right hand corner of the
screen to link the user to other apps in Fedora Infrastructure.
If the fedmenu.url value is not defined in the config, then nothing is
display (so FAS can be reused other places that don't want to use this
shim).
As a nice bonus, on user profile pages we'll also display a little
button with their avatar than takes you to views of that user in other
infra apps (so you can quickly jump to see what packages they own or
what their datagrepper activity is, etc..).
> Add fedmenu!

- fas/forms/group.py
- fas/forms/people.py
This makes sure the options for certain forms are loaded as needed instead of on start of the web app.
> Fix initializing choices on load

- fas/user.py
This hides inactive accounts by default. Clients can still
request them by setting return_non_active=True.
> Don't return inactive accounts by default

- fas/user.py
This patch allows API clients to request to receive only uesrs
with a specific status.
> Allow to specify a status for the list call

- README.rst
On a fresh install there is missing dependencies. Also added additional information after appending info to shells rc file
```
Collecting cffi>=1.4.1 (from cryptography->fas==3.0.0)
Downloading cffi-1.6.0.tar.gz (397kB)
100% |████████████████████████████████| 399kB 1.2MB/s 
Complete output from command python setup.py egg_info:
gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
```
and
```
Failed building wheel for pillow
...
...
...
' using --disable-%s, aborting' % (f, f))
ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting
----------------------------------------
Command "/home/skrzepto/.virtualenvs/fas-python2.7/bin/python2.7 -u -c "import …
```
> Updating readme to add missing dependencies

- fas/user.py
- fas/validators.py
This email validation is the same check the library we use for
sending email (turbomail) uses.
Currently, it is possible to get email addresses like whatever.@domain.com
(note the . before @) into FAS, and we will crash as soon as we
try to send an actual email.
> Validate email the same way turbomail does it

- fas/subscribers/login.py
- fas/subscribers/people.py
People model doesn't have `last_logged` attribute, but has a `login_timestamp`.
Updated old reference to `last_logged` with the `login_timestamp`
> Replace last_logged attribute by the login_timestamp

- fas/templates/fedoraproject/groups/details.xhtml
- fas/views/groups.py
And first check if there is a group, then retrieve its members, otherwise
we end up with no group found, not because it doesn't exist but because
there are no members anymore.
> Allow accessing group profile by their name instead of id

- fas/validators.py
The valid_ssh_key is not a global, but instance-local.
Also, {} is python 2.7-only syntax, while we run on RHEL6, which has python 2.6.
> Fix ssh key updating

- fas/util.py
- fas/views/people.py
There was two problem:
- settings[configname] raises a KeyError if the key isn't in the settings,
so the second part of the line `or default_config` is never used.
We fixed this.
- Config.get('locale.available') returns None if there are no
locale.available, but None cannot be split, so instead we make sure that
if there are no locale.available we get an empty string which can be
split.
> If the list of local.available is empty we should be able to cope with it

- fas/views/groups.py
fixes: #187
Previously, if a user is logged in and looking at a group that
they are a member of, they would not be shown in the members list
This makes the user shown in the list of all the users for the current
group
> show the currently logged in user in the groups user list

- fas/views/groups.py
- fas/views/people.py
Previously it was possible with the pagination URLs on the people and groups lists to request page 0 or a negative page, for example:
https://admin.stg.fedoraproject.org/fas3/groups/page/-4
https://admin.stg.fedoraproject.org/fas3/people/page/0
this change detects if a page under 1 is requested on the groups list and the users list, and returns the 400 error as was previously done if the number of pages exceeded the available number of pages.
> return a 400 if page 0 or a negative page is requested

- fas/theme/default/templates/people/profile.xhtml
Fixes issue #231 
Previously, if a group did not have a displayname set, the involvement section in a user's profile page would show "None" rather than the group's name. Now if a displayname for a group is not set, it falls back to use the group's name.
> show groupname instead of None if no displayname is set

- fas/security.py
the init method of the MembershipValidator class previously had some lines in it that converted self.group to a list if it was of str or unicode type, rather than a list:
if type(group) is str or unicode:
self.group = [group]
if type(group) is list:
self.group = group
Based on my limited knowledge of class inheritance, it appears that these conversions were overwritten my the init function in the `RoleValidator` class. So when the validate method in the MembershipValidator class tried to perform the intersections of the sets to see if the groupname was in the list of permitted groups, self.group was not a list anymore, and always returned False.
This commit moves the logic of converting str and unicode types into the validate method of MembershipValidator, and fixes the symptoms described …
> make group admin controls show if you are a group admin

- devel-ansible/roles/dev/tasks/main.yml
- fas/scripts/admin.py
* add python-faker as dep in the vagrant setup to make the vagrant setup work again
* make fake data more real - Adds code to the fake user generator to do a few things
to make testing themes easier
* autogenerate groups, rather than using a static list, and
generate more groups, primarily so we get pagination on
the groups list
* add all users to the fas-users list so we have at least one
group with a lot of users
* make users be a member of more than one group
> Fas 3.0 develenv

- fas/lib/captcha.py
previously, the CAPTCHA was not rendering when on the
create new account page. The error message from PIL
suggested using the 4-tuple of the image size in the
paste call, so that is what this does, and it fixes the
issue.
Fixes: Issue #244
> make CAPTCHA render

- fas/notifications/email.py
- fas/views/register.py
* First up, this adds a debug message so that when you are testing account verification, the email that is sent is diplayed as a debug message, so you can get at the verification URL
* Next, it fixes the redirect_to, which requires at least 2 arguments, but we were only providing one.
* Finally, after fixing the redirect_to issue, the following error appeared when trying to verify an account:
```
ProgrammingError: (psycopg2.ProgrammingError) missing FROM-clause entry for table "accountstatus"
LINE 1: UPDATE people SET password_token=NULL, status=AccountStatus....
^
[SQL: 'UPDATE people SET password_token=%(password_token)s, status=%(status)s, update_timestamp=CURRENT_TIMESTAMP WHERE people.id = %(people_id)s'] [parameters: {'status': <AccountStatus.ACTIVE: 1>, 'people_id': 10007, …
```
> fix account verification process

- fas/subscribers/people.py
The arguments for the redirect_to appear to have changed, causing issue #250 this PR fixes the arguments.
fixes issue #250
> update redirect_to args for password change after timeout
