fedora-infra/fas

fas/utils/__init__.py
See https://github.com/fedora-infra/fas/pull/103#issuecomment-70413422.
Signed-off-by: Ricky Elrod <ricky@elrod.me>
=> Use a custom UTC class to fix isoformat instead

fas/api/groups.py
Fixes #108.
Signed-off-by: Ricky Elrod <ricky@elrod.me>
=> Make the groups list API endpoint work.

fas/api/groups.py
But in the groups api this time
Signed-off-by: Ricky Elrod <ricky@elrod.me>
=> Fix typos similar to #100

plugins/fas-plugin-yubikey/fas_yubikey/__init__.py
This is causing the plugin to fail in staging.  It looks like it was removed
from everywhere else in FAS (and it's not packaged for Fedora/EPEL afaik).
=> Remove fancyflash from the yubikey plugin.

fas/static/theme/fas/css/style.css, fas/templates/user/view.html
=> Apply word-wrap on SSH key in user view

fas/models/people.py
A sequence starts with a number not a string.
=> Fix creating the DB in postgresql

fas/forms/people.py, fas/models/people.py, fas/templates/fedoraproject/people/edit-infos.xhtml, fas/templates/fedoraproject/people/profile.xhtml
This is an untested attempt to get rid of the gpg_id as discussed in #53 . A validator for the GPG fingerprint is still missing here, also I do not know if it looks good. Feedback welcome! :-)
=> Store and show only GPG fingerprint instead of ID

fas/scripts/admin.py
This change is needed when the DB is empty, we need to populate it
with some data then.
=> Fix generating fake data

fas.cfg.sample, fas.spec, fas/fpca.py, fas/model/fasmodel.py, fas/user.py, fas2.sql, updates/fas2-0.11.0_to_0.12.0.sql
=> Add hook points for automated spamcheck

NEWS
=> update NEWS file

fas.cfg.sample, fas.spec, fas/fpca.py, fas/model/fasmodel.py, fas/user.py, fas2.sql, updates/fas2-0.11.0_to_0.12.0.sql
Some features were developed directly into master to work around security issues, this merged those to develop.
=> Ported all master features back to develop

fas/fpca.py, fas/user.py
=> Use the python-requests automatic json encoding

fas/fpca.py, fas/user.py
=> General fixes

fas/release.py
=> Bump version to 0.12.0 for release

fas/fpca.py, fas/user.py
=> Fix the case where spamcheck is disabled

fas.cfg.sample, fas/user.py, fas/validators.py
=> Allow blocking by email address suffix

fas/user.py, fas/validators.py
=> Make sure email address is lowercase

fas/group.py, fas/user.py, fas/validators.py
=> Create checks that we get no overlapping user and group names

fas.cfg.sample, fas/model/fasmodel.py, fas/safasprovider.py, fas/templates/user/view.html, fas/user.py, fas2.sql, updates/fas2-0.13.1_to_0.14.0.sql
=> Add IPA sync code

NEWS, fas.spec, fas/release.py
=> Bump version to 0.14.0

fas/views/register.py
#173 
If the irc nick field is empty set it to None instead
=> Issue #173: if the irc nick field is empty set it to None instead

fas/models/configs.py, fas/models/group.py, fas/models/people.py, fas/scripts/admin.py, fas/subscribers/login.py, fas/views/register.py
=> [FAS3] Fix login, register and models

fas/safasprovider.py, fas/user.py
=> Get rid of IPA sessions

fas.spec
This commit updates the specfile to reflect the new
locations of the theme files -- static and templates
related: PR #227
=> update spec to reflect recent changes to theme location

fas/theme/fedoraproject/templates/groups/list.xhtml
change the html structure of the groups listing page for
the fedorabootstrap theme
=> style fedoraproject theme groups page to fedorabootstrap

fas/theme/fedoraproject/templates/login.xhtml
changes the login template for the login page
of the fedoraproject theme to match the fedorabootstrap
style
=> restyle the fedoraproject theme login page

devel-ansible/files/development.ini, devel-ansible/roles/dev/tasks/main.yml
the development.ini used in the vagrant setup is now based on its
own that we keep in devel-ansible/files
=> fix vagrant setup not working after recent changes to development.ini

fas/subscribers/login.py, fas/views/admin.py, fas/views/register.py
a change to the redirect_to function changed the arguments
and a bunch of calls to this function were not changed.
this fixes those calls
=> change the remainder of the redirect_to missing args

fas/safasprovider.py
=> No longer pass this explicit user_name attribute, we already have user

fas/templates/user/new.html, po/fas.pot
Making the implications clearer for privacy.
=> Add specificity to new account note
